version: '3.8'
services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    container_name: postgres
    environment:
      - POSTGRES_DB=master
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

      # - DB_HOST=db        # Use the service name 'db'
      # - DB_NAME=master
      # - DB_USER=postgres
      # - DB_PASSWORD=root  # Added DB_PASSWORD to match your PostgreSQL setup
      # - DB_PORT=5432

    ports:
      - 5432:5432
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
   
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 4000:4000
    environment:
      # - POSTGRES_DB=master
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=root
      - DB_HOST=db        # Use the service name 'db'
      - DB_NAME=master
      - DB_USER=postgres
      - DB_PASSWORD=root  # Added DB_PASSWORD to match your PostgreSQL setup
      - DB_PORT=5432
    stdin_open: true
    tty: true
volumes: 
  db:
# networks:
#   app-network:
#     name: AppNetwork
#     driver: bridge